source 'https://rubygems.org'
ruby '2.2.2'
gem 'rails'
gem 'pg'
gem 'sass-rails'
gem 'uglifier'
gem 'coffee-rails'
gem 'jquery-rails'
gem 'turbolinks', :git => 'https://github.com/rails/turbolinks.git'
gem 'jbuilder'
gem 'sdoc', group: :doc
gem 'materialize-sass'
gem 'devise'
gem 'toastr-rails'
gem 'mandrill-api', require: 'mandrill'
gem 'omniauth'
gem 'omniauth-google-oauth2'
gem 'dotenv-rails'
gem 'activeadmin', github: 'activeadmin'
gem 'active_skin'
gem 'paperclip'
gem 'redcarpet', :git => 'https://github.com/vmg/redcarpet.git'
gem 'coderay'
group :development, :test do
  gem 'byebug'
  gem 'web-console'
  gem 'spring'
end
